### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by Mohammad8234** [T8RIN/ImageToolbox#1108] opened 2024-05-27 16:52 UTC
Device: M2102J20SG (POCO - vayu), SDK: 33 (13), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'M0.O M0.G.V' on a null object reference in method 'void M0.G.J(M0.G)'at M0.G.J(SourceFile:1)at M0.G.P(SourceFile:20)at M0.w0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.v0.o(SourceFile:188)at N0.b0.doFrame(SourceFile:34)at N0.Y.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)at android.view.Choreographer.doCallbacks(Choreographer.java:1089)at android.view.Choreographer.doFrame(Choreographer.java:998)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:211)at android.os.Looper.loop(Looper.java:300)at android.app.ActivityThread.main(ActivityThread.java:8289)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by T8RIN** [comment] 2024-05-27 17:02
Duplicate of #1039

**Closed by T8RIN** 2024-05-27 17:02 UTC
