### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by nascentphilosopher** [T8RIN/ImageToolbox#1215] opened 2024-07-21 05:01 UTC
Device: moto g31 (motorola - coful), SDK: 31 (12), App: 2.9.1-alpha01 (145)java.lang.IllegalArgumentException: MutableState containing Color(0.0, 0.0, 0.0, 0.0, sRGB IEC61966-2.1) cannot be saved using the current SaveableStateRegistry. The default implementation only supports types which can be stored inside the Bundle. Please consider implementing a custom Saver for this class and pass it as a stateSaver parameter to rememberSaveable().at M0.a.d(SourceFile:86)at M0.a.a(SourceFile:1)at D0.w.f(SourceFile:127)at D0.x.j(SourceFile:64)at D0.x.i(SourceFile:6)at D0.J0.a(SourceFile:106)at D0.p.a(SourceFile:5)at D0.x.o(SourceFile:9)at m1.G.i(SourceFile:22)at m1.G.h(SourceFile:121)at m1.B.E(SourceFile:160)at f0.O.a(SourceFile:34)at d0.l.b(SourceFile:21)at d0.m.l(SourceFile:837)at Z.M.l(SourceFile:1156)at m1.D.d(SourceFile:74)at o1.t.d(SourceFile:38)at W0.V.e(SourceFile:1)at o1.y.d(SourceFile:15)at W0.V.e(SourceFile:1)at o1.y.d(SourceFile:15)at c0.D.e(SourceFile:99)at o1.y.d(SourceFile:15)at h9.H.b(SourceFile:73)at N0.s.e(SourceFile:56)at N0.t.a(SourceFile:48)at N0.u.c(SourceFile:140)at o1.h0.a(SourceFile:3)at o1.I.w0(SourceFile:133)at o1.D.M(SourceFile:17)at o1.D.N(SourceFile:18)at o1.P.c(SourceFile:8)at o1.P.m(SourceFile:138)at o1.P.g(SourceFile:94)at o1.P.g(SourceFile:106)at o1.P.f(SourceFile:44)at o1.I.w0(SourceFile:60)at o1.I.d(SourceFile:91)at c0.q.d(SourceFile:256)at o1.t.d(SourceFile:38)at c0.D.e(SourceFile:99)at o1.y.d(SourceFile:15)at h9.H.b(SourceFile:73)at N0.s.e(SourceFile:114)at N0.t.a(SourceFile:48)at N0.u.c(SourceFile:140)at o1.h0.a(SourceFile:3)at o1.I.w0(SourceFile:133)at o1.D.M(SourceFile:17)at o1.D.N(SourceFile:18)at o1.P.c(SourceFile:8)at o1.P.m(SourceFile:138)at o1.P.j(SourceFile:90)at p1.t.s(SourceFile:36)at p1.t.dispatchDraw(SourceFile:17)at android.view.View.draw(View.java:22769)at android.view.View.updateDisplayListIfDirty(View.java:21641)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)at android.view.View.updateDisplayListIfDirty(View.java:21597)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4665)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4393)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3515)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2303)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)at android.view.Choreographer.doCallbacks(Choreographer.java:845)at android.view.Choreographer.doFrame(Choreographer.java:780)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)at android.os.Handler.handleCallback(Handler.java:980)at android.os.Handler.dispatchMessage(Handler.java:104)at android.os.Looper.loopOnce(Looper.java:238)at android.os.Looper.loop(Looper.java:357)at android.app.ActivityThread.main(ActivityThread.java:8098)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Comment by T8RIN** [comment] 2024-07-21 06:56
Duplicate of #1214

**Closed** 2024-07-21 19:18 UTC
