### ISSUE TITLE
Update notification keeps popping up

### ISSUE THREAD

**Issue by MrScreemi** [T8RIN/ImageToolbox#503] opened 2023-10-23 11:05 UTC
Hi

Since the last update I got an issue. The update notification keeps popping up even when swiped away. After about 1 second it just slides up again. 

Maybe someone else got this issue or there is an easy fix for it?

I am on:
Pixel 6
Android 14

I made a little video displaying the issue:

https://youtube.com/shorts/xiL20Ut11Q0?si=_8RUS1eTyO65p60K

**Comment by T8RIN** [comment] 2023-10-23 11:07
Duplicate of #499

**Comment by T8RIN** [comment] 2023-10-23 11:07
For now you can disable showing this dialog

**Comment by MrScreemi** [comment] 2023-10-23 12:03
> For now you can disable showing this dialog

That leaves one question: How and where?

Sorry for the dublicate. Maybe someone could merge the issues.

**Comment by T8RIN** [comment] 2023-10-23 12:12
In settings 👀

**Comment by T8RIN** [comment] 2023-10-23 12:12
Maybe you should try installing last version now, it also have foss variation

**Comment by Perdellian** [comment] 2023-10-23 12:23
workaround:
1. downgrade to the previous version available in F-Droid (2.0.5)
3. disable the "Check for updates" setting, as pictured below
4. Re-upgrade

Seems to have fixed it for me.
Note: I only saw this app in F-Droid and decided to try it out with the appearance of this update, so I have never previously had installed any version prior to 2.4.1.

**Comment by T8RIN** [comment] 2023-10-23 12:30
How it is going on latest alpha?

**Comment by pandalamp** [comment] 2023-10-24 04:56
> In settings 👀

Even if you can open the settings between pop-ups, the notification blocks the settings from being scrolled while it is open and the option is at the bottom 😑

**Comment by T8RIN** [comment] 2023-10-24 04:58
> > In settings 👀
> 
> Even if you can open the settings between pop-ups, the notification blocks the settings from being scrolled while it is open and the option is at the bottom 😑

By the way, I don’t know why this happened, because in my tests everything seems to be okay

**Closed** 2023-10-30 11:42 UTC
Labels: bug, duplicate
