### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by DP-Hridayan** [T8RIN/ImageToolbox#1068] opened 2024-05-10 06:24 UTC
Device: 7 Pro (realme - RMX2170), SDK: 34 (14), App: 2.8.2-alpha01 (137)java.lang.NullPointerException: Attempt to read from field 'N0.O N0.G.M' on a null object reference in method 'void N0.G.J(N0.G)'at N0.G.J(SourceFile:1)at N0.G.P(SourceFile:20)at N0.x0.h(SourceFile:5)at d0.y.a(SourceFile:11)at d0.J.P(SourceFile:26)at d0.a.N(SourceFile:3)at c0.u.j(SourceFile:51)at c0.u.i(SourceFile:6)at c0.w0.o(SourceFile:174)at O0.e0.doFrame(SourceFile:34)at O0.c0.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:878)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:205)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8243)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)Suppressed: K6.g: [O0.f0@c26827, O0.J0@3ac6ad4, F{Cancelling}@cee447d, d0@fff6f72]

**Comment by T8RIN** [comment] 2024-05-10 09:16
Duplicate of #1039

**Closed by T8RIN** 2024-05-10 09:16 UTC
