### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by J4k3v3** [T8RIN/ImageToolbox#990] opened 2024-04-24 10:19 UTC
Device: Redmi Note 8 Pro (Redmi - begonia), SDK: 33 (13), App: 2.8.0 (134)java.lang.IllegalArgumentException: red = 0.41960785, green = 0.2627451, blue = 0.30588236, alpha = 1.0000001 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)at androidx.compose.ui.graphics.a.F(SourceFile:3)at androidx.compose.ui.graphics.a.b(SourceFile:484)at s0.u.c(SourceFile:17)at Y7.q.a(SourceFile:121)at Y7.q.m(SourceFile:28)at h0.b.m(SourceFile:54)at S.e.V(SourceFile:314)at S.e.W(SourceFile:739)at Y7.F.m(SourceFile:35)at Z.s.M(SourceFile:585)at Z.s.T(SourceFile:130)at Z.s.p(SourceFile:239)at Z.s.K(SourceFile:30)at Z.z.y(SourceFile:21)at Z.P0.w(SourceFile:111)at Z.N0.n(SourceFile:542)at K0.i0.doFrame(SourceFile:7)at K0.g0.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)at android.view.Choreographer.doCallbacks(Choreographer.java:899)at android.view.Choreographer.doFrame(Choreographer.java:827)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:201)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7896)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)Suppressed: C6.g: [Z.x0@5eb02f1, K0.N0@75bded6, u0{Cancelling}@f874557, h0@c033844]

**Comment by T8RIN** [comment] 2024-04-24 10:58
How to reproduce?

**Comment by J4k3v3** [comment] 2024-04-24 11:13
IDK, I just switching the downbar buttons (Edit / Create / Image / Tools) and get this bug

**Comment by J4k3v3** [comment] 2024-04-24 11:14
https://github.com/T8RIN/ImageToolbox/assets/111687331/ac4bbc0a-cbdc-49d7-9bf1-47160d30c267

**Comment by T8RIN** [comment] 2024-04-24 11:30
Thanks!

**Comment by J4k3v3** [comment] 2024-04-24 11:42
NP!) And I wanna ask you. What different between "foss" and default versions of Image Toolbox?

**Comment by T8RIN** [comment] 2024-04-24 11:50
Foss doesn't have google deps, fe there are no auto background removal because it's relies on google mlkit

**Comment by J4k3v3** [comment] 2024-04-24 12:32
THX!)

**Comment by mackiecarr89** [comment] 2024-04-24 15:30
Crashes after selecting an image in the material you palette generator. 

Samsung Galaxy S20

[Bug] App Crash: IllegalArgumentException

Device: SM-G988W (samsung - z3q), SDK: 33 (13), App: 2.8.0 (134)

java.lang.IllegalArgumentException: Start padding must be non-negative
	at x.A0.<init>(SourceFile:74)
	at androidx.compose.foundation.layout.a.e(SourceFile:24)
	at R3.E7.r(SourceFile:333)
	at ea.m.r(SourceFile:837)
	at g0.b.b(SourceFile:46)
	at g0.b.r(SourceFile:9)
	at r.m.b(SourceFile:1246)
	at r.m.h(SourceFile:2669)
	at g0.b.a(SourceFile:46)
	at g0.b.h(SourceFile:9)
	at y8.B.a(SourceFile:789)
	at r.n.a(SourceFile:2467)
	at r.n.j(SourceFile:64)
	at g0.b.j(SourceFile:54)
	at l7.E.b(SourceFile:955)
	at l7.E.a(SourceFile:310)
	at R3.D7.n(SourceFile:97)
	at Y9.P.i(SourceFile:1246)
	at Y9.P.q(SourceFile:13)
	at Y9.P.r(SourceFile:3451)
	at g0.b.b(SourceFile:46)
	at g0.b.r(SourceFile:9)
	at Q9.f.h(SourceFile:184)
	at g0.b.a(SourceFile:46)
	at g0.b.h(SourceFile:9)
	at y.j.r(SourceFile:184)
	at g0.b.b(SourceFile:46)
	at g0.b.r(SourceFile:9)
	at s.P.a(SourceFile:455)
	at s.P.j(SourceFile:184)
	at g0.b.j(SourceFile:54)
	at Y.s.M(SourceFile:585)
	at Y.s.V(SourceFile:29)
	at androidx.compose.foundation.lazy.layout.a.b(SourceFile:98)
	at y.n.d(SourceFile:106)
	at s.z0.a(SourceFile:394)
	at s.z0.j(SourceFile:304)
	at g0.b.j(SourceFile:54)
	at Y.s.M(SourceFile:585)
	at Y.s.V(SourceFile:29)
	at A.m0.c(SourceFile:70)
	at androidx.compose.foundation.lazy.layout.a.d(SourceFile:108)
	at u.Z.b(SourceFile:2496)
	at u.Z.j(SourceFile:375)
	at g0.b.j(SourceFile:54)
	at Y.s.M(SourceFile:585)
	at Y.s.T(SourceFile:130)
	at Y.s.p(SourceFile:239)
	at Y.s.K(SourceFile:30)
	at Y.z.y(SourceFile:21)
	at Y.P0.w(SourceFile:111)
	at Y.N0.k(SourceFile:587)
	at J0.i0.doFrame(SourceFile:7)
	at J0.g0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by T8RIN** [comment] 2024-04-24 15:31
Just fixed right now, the patch will be shipped till the evening, are there any other issues?

**Comment by J4k3v3** [comment] 2024-04-24 16:40
I think not, but if anything - we tell you!)

**Comment by T8RIN** [comment] 2024-04-24 16:42
Okay! Could you please also try the latest actions build to check if it's fixed?

**Comment by T8RIN** [comment] 2024-04-24 18:28
Here you can download it -> https://github.com/T8RIN/ImageToolbox/actions/runs/8820875307/artifacts/1444352841

**Comment by J4k3v3** [comment] 2024-04-24 18:44
So, after a little test I can tell you - i don't find any bugs!) No bug with downbar, no any other bugs

Thanks for you sonic fast solution of the problem!!)

**Comment by T8RIN** [comment] 2024-04-24 18:54
Glad that it's working, there is also a new version building, because the last one didn't help others :(

**Comment by J4k3v3** [comment] 2024-04-24 19:52
Ouch :(

You can drop new version to me, I'll test when I can :)

**Comment by T8RIN** [comment] 2024-04-25 05:37
Okay :) I think i can lower the Compose version to overcome this bug at least for now

**Comment by T8RIN** [comment] 2024-04-25 12:19
https://issuetracker.google.com/issues/336815323 fixed in next lib release, for now i'll rollback to use it normally

**Closed by T8RIN** 2024-04-25 12:19 UTC
