### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by Sandhusaab376** [T8RIN/ImageToolbox#1065] opened 2024-05-09 13:37 UTC
Device: M2101K7BI (Redmi - secret), SDK: 33 (13), App: 2.8.2-alpha01 (137)java.lang.NullPointerException: Attempt to read from field 'M0.P M0.H.V' on a null object reference in method 'void M0.H.J(M0.H)'at M0.H.J(SourceFile:1)at M0.H.P(SourceFile:20)at M0.x0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.u0.o(SourceFile:188)at N0.Z.doFrame(SourceFile:34)at N0.X.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1384)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)at android.view.Choreographer.doCallbacks(Choreographer.java:1013)at android.view.Choreographer.doFrame(Choreographer.java:904)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:211)at android.os.Looper.loop(Looper.java:300)at android.app.ActivityThread.main(ActivityThread.java:8232)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)Suppressed: S8.g: [N0.a0@c916e46, N0.D0@9a97807, t0{Cancelling}@c246d34, Y@f00875d]

**Comment by Sandhusaab376** [comment] 2024-05-09 13:40
I am not able to make pdf

**Comment by T8RIN** [comment] 2024-05-10 09:17
Duplicate of #1039

**Comment by T8RIN** [comment] 2024-05-10 09:18
That's alpha, so this is expected, also this bug in compose ui library

**Closed by T8RIN** 2024-05-10 09:17 UTC
