### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by Filippide8864** [T8RIN/ImageToolbox#1082] opened 2024-05-17 10:41 UTC
Device: Lenovo TB-X306X (Lenovo - X306X), SDK: 30 (11), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'M0.O M0.G.V' on a null object referenceat M0.G.J(SourceFile:1)at M0.G.P(SourceFile:20)at M0.w0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.v0.o(SourceFile:188)at N0.b0.doFrame(SourceFile:34)at N0.Y.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)at android.view.Choreographer.doCallbacks(Choreographer.java:797)at android.view.Choreographer.doFrame(Choreographer.java:728)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:959)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loop(Looper.java:223)at android.app.ActivityThread.main(ActivityThread.java:7785)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)Suppressed: T8.g: [N0.c0@fc126fc, N0.F0@2069185, t0{Cancelling}@f00abda, Z@c41c80b]

**Comment by T8RIN** [comment] 2024-05-17 10:43
Duplicate of #1039

**Closed by T8RIN** 2024-05-17 10:43 UTC
