### ISSUE TITLE
[Bug] App Crash when creating PDF from images: NullPointerException

### ISSUE THREAD

**Issue by D3SOX** [T8RIN/ImageToolbox#1083] opened 2024-05-17 14:23 UTC
Tried to create a PDF from 2 screenshot images captured using [Screenshot Assistant](https://play.google.com/store/apps/details?id=pl.waskysoft.screenshotassistant)

Device: Pixel 8 Pro (google - husky), SDK: 34 (14), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'N0.O N0.G.M' on a null object reference in method 'void N0.G.J(N0.G)'at N0.G.J(SourceFile:1)at N0.G.P(SourceFile:20)at N0.y0.h(SourceFile:5)at d0.y.a(SourceFile:11)at d0.J.W(SourceFile:26)at d0.a.U(SourceFile:3)at c0.u.j(SourceFile:51)at c0.u.i(SourceFile:6)at c0.v0.n(SourceFile:174)at O0.b0.doFrame(SourceFile:34)at O0.Z.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)at android.view.Choreographer.doCallbacks(Choreographer.java:1008)at android.view.Choreographer.doFrame(Choreographer.java:934)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)at android.os.Handler.handleCallback(Handler.java:959)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loopOnce(Looper.java:232)at android.os.Looper.loop(Looper.java:317)at android.app.ActivityThread.main(ActivityThread.java:8501)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)Suppressed: L6.g: [O0.c0@493c50d, O0.G0@e030cc2, F{Cancelling}@53bbad3, a0@f8d0610]

**Comment by T8RIN** [comment] 2024-05-17 15:02
Duplicate of #1049

**Closed** 2024-05-17 15:03 UTC

**Comment by D3SOX** [comment] 2024-05-17 15:46
Oops sorry for not searching first
