### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by Csar67** [T8RIN/ImageToolbox#1079] opened 2024-05-15 22:55 UTC
Device: 220333QAG (Redmi - fog), SDK: 33 (13), App: 2.8.2-alpha01 (137)java.lang.NullPointerException: Attempt to read from field 'M0.P M0.H.V' on a null object reference in method 'void M0.H.J(M0.H)'at M0.H.J(SourceFile:1)at M0.H.P(SourceFile:20)at M0.x0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.u0.o(SourceFile:188)at N0.Z.doFrame(SourceFile:34)at N0.X.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1489)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1499)at android.view.Choreographer.doCallbacks(Choreographer.java:1114)at android.view.Choreographer.doFrame(Choreographer.java:1026)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:211)at android.os.Looper.loop(Looper.java:300)at android.app.ActivityThread.main(ActivityThread.java:8410)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by T8RIN** [comment] 2024-05-16 09:29
Duplicate of #1039

**Closed** 2024-05-16 09:29 UTC
