### ISSUE TITLE
Picker mode crashes the app (any picture)

### ISSUE THREAD

**Issue by nexus226** [T8RIN/ImageToolbox#1100] opened 2024-05-23 12:27 UTC
Using FOSS version
[Bug] App Crash: ArrayIndexOutOfBoundsException

Device: SM-G780G (samsung - r8q), SDK: 33 (13), App: 2.8.2-alpha02 (138)

java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=2 dst.length=16 dstPos=3 length=-1
	at java.lang.System.arraycopy(Native Method)
	at V4.m.v(SourceFile:12)
	at e0.d.a(SourceFile:16)
	at N0.G.x(SourceFile:73)
	at N0.y0.c(SourceFile:7)
	at d0.q.a(SourceFile:224)
	at d0.J.W(SourceFile:26)
	at d0.s.a(SourceFile:36)
	at d0.J.W(SourceFile:26)
	at d0.a.U(SourceFile:3)
	at c0.u.j(SourceFile:51)
	at c0.u.i(SourceFile:6)
	at c0.v0.n(SourceFile:174)
	at O0.b0.doFrame(SourceFile:34)
	at O0.Z.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: L6.g: [O0.c0@7f0019e, O0.G0@fe3047f, F{Cancelling}@841cc4c, a0@f0b5495]

**Comment by T8RIN** [comment] 2024-05-23 12:28
Duplicate of #1047

**Closed by T8RIN** 2024-05-23 12:28 UTC
Labels: bug
