### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by thomasfrobieter** [T8RIN/ImageToolbox#1089] opened 2024-05-19 14:25 UTC
Edit a single picture, add the "Achromatolamie"-Filter and then remove it with the circle minus icon on the bottom left.

Device: Pixel 6a (google - bluejay), SDK: 34 (14), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'M0.O M0.G.V' on a null object reference in method 'void M0.G.J(M0.G)'at M0.G.J(SourceFile:1)at M0.G.P(SourceFile:20)at M0.w0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.v0.o(SourceFile:188)at N0.b0.doFrame(SourceFile:34)at N0.Y.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)at android.view.Choreographer.doCallbacks(Choreographer.java:1008)at android.view.Choreographer.doFrame(Choreographer.java:934)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)at android.os.Handler.handleCallback(Handler.java:959)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loopOnce(Looper.java:232)at android.os.Looper.loop(Looper.java:317)at android.app.ActivityThread.main(ActivityThread.java:8501)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by T8RIN** [comment] 2024-05-19 14:42
Duplicate of #1039

**Closed by T8RIN** 2024-05-19 14:42 UTC
