### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by Leaghack** [T8RIN/ImageToolbox#1104] opened 2024-05-26 11:23 UTC
Device: moto g34 5G (motorola - fogos), SDK: 34 (14), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'M0.O M0.G.V' on a null object reference in method 'void M0.G.J(M0.G)'at M0.G.J(SourceFile:1)at M0.G.P(SourceFile:20)at M0.w0.h(SourceFile:5)at c0.y.a(SourceFile:11)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.v0.o(SourceFile:188)at N0.b0.doFrame(SourceFile:34)at N0.Y.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1341)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)at android.view.Choreographer.doCallbacks(Choreographer.java:952)at android.view.Choreographer.doFrame(Choreographer.java:878)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)at android.os.Handler.handleCallback(Handler.java:1000)at android.os.Handler.dispatchMessage(Handler.java:104)at android.os.Looper.loopOnce(Looper.java:242)at android.os.Looper.loop(Looper.java:362)at android.app.ActivityThread.main(ActivityThread.java:8393)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)Suppressed: T8.g: [N0.c0@405ea10, N0.F0@c35b909, t0{Cancelling}@736b70e, Z@e6652f]

**Comment by T8RIN** [comment] 2024-05-26 11:30
Duplicate of #1039

**Closed** 2024-05-26 11:30 UTC
