### ISSUE TITLE
[Bug] color picker crashes app

### ISSUE THREAD

**Issue by deathblade666** [T8RIN/ImageToolbox#1119] opened 2024-06-01 23:20 UTC
**Describe the bug**
App crashes when I select an image to run the color picker on

**To Reproduce**
1.Open image toolbox
2. Select color picker
3. Select image

**Expected behavior**
Not to crash?

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: pixel 6
 - OS: latest Android beta

**Error message**
``` 
[Bug] App Crash: ArrayIndexOutOfBoundsException

Device: Pixel 6 (google - oriole), SDK: 34 (14), App: 2.8.2-alpha02 (138)

java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=2 dst.length=16 dstPos=3 length=-1
	at java.lang.System.arraycopy(Native Method)
	at d7.m.j(SourceFile:12)
	at d0.d.a(SourceFile:16)
	at M0.G.y(SourceFile:73)
	at M0.w0.c(SourceFile:7)
	at c0.q.a(SourceFile:224)
	at c0.J.e(SourceFile:26)
	at c0.s.a(SourceFile:36)
	at c0.J.e(SourceFile:26)
	at c0.a.c(SourceFile:3)
	at b0.u.j(SourceFile:51)
	at b0.u.i(SourceFile:6)
	at b0.v0.o(SourceFile:188)
	at N0.b0.doFrame(SourceFile:34)
	at N0.Y.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:941)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8674)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
	Suppressed: T8.g: [N0.c0@c3d8864, N0.F0@719bacd, t0{Cancelling}@46d2f82, Z@7830693]
```

**Comment by T8RIN** [comment] 2024-06-02 02:20
This is a Duplicate of #1047, use the latest alpha of app👀 (2.8.2-alpha03)

**Closed by T8RIN** 2024-06-02 02:20 UTC
Labels: bug
