### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by OctoberNicole** [T8RIN/ImageToolbox#1052] opened 2024-05-07 04:28 UTC
Device: Note 14 (Ulefone - Note_14), SDK: 31 (12), App: 2.8.2-alpha01 (137)java.lang.NullPointerException: Attempt to read from field 'N0.O N0.G.M' on a null object reference in method 'void N0.G.J(N0.G)'at N0.G.J(SourceFile:1)at N0.G.P(SourceFile:20)at N0.x0.h(SourceFile:5)at d0.y.a(SourceFile:11)at d0.J.P(SourceFile:26)at d0.a.N(SourceFile:3)at c0.u.j(SourceFile:51)at c0.u.i(SourceFile:6)at c0.y0.a(SourceFile:106)at c0.o.a(SourceFile:5)at c0.u.o(SourceFile:9)at L0.G.i(SourceFile:35)at L0.G.h(SourceFile:121)at L0.B.p(SourceFile:160)at E.V.a(SourceFile:34)at F.i.c(SourceFile:123)at f7.n.N(SourceFile:2107)at f7.n.P(SourceFile:231)at F.l.m(SourceFile:554)at A8.p.m(SourceFile:1878)at L0.D.a(SourceFile:74)at N0.v.a(SourceFile:38)at v0.W.f(SourceFile:1)at N0.B.a(SourceFile:15)at Aa.d.c(SourceFile:38)at l6.d.z(SourceFile:114)at m0.s.a(SourceFile:48)at m0.t.c(SourceFile:140)at N0.m0.a(SourceFile:3)at N0.M.w0(SourceFile:133)at N0.G.M(SourceFile:17)at N0.V.c(SourceFile:3)at N0.V.k(SourceFile:100)at O0.x.y(SourceFile:8)at N0.G.k(SourceFile:41)at A2.g.o(SourceFile:121)at y.r.a(SourceFile:17)at w.n.a(SourceFile:323)at y.G0.a(SourceFile:29)at y.z0.o(SourceFile:72)at y.O.w(SourceFile:59)at Z4.a.n(SourceFile:9)at F6.I.run(SourceFile:95)at O0.d0.V(SourceFile:7)at O0.c0.doFrame(SourceFile:10)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1103)at android.view.Choreographer.doCallbacks(Choreographer.java:896)at android.view.Choreographer.doFrame(Choreographer.java:810)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1090)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:201)at android.os.Looper.loop(Looper.java:288)at android.app.ActivityThread.main(ActivityThread.java:7924)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)Suppressed: K6.g: [O0.J0@7098a43, c0.h@a0278c0, F{Cancelling}@85819f9, d0@5031d3e]

**Comment by T8RIN** [comment] 2024-05-07 11:19
When?

**Comment by T8RIN** [comment] 2024-05-10 09:17
Duplicate of #1039

**Closed by T8RIN** 2024-05-10 09:17 UTC

**Comment by OctoberNicole** [comment] 2024-05-12 08:15
This was happening while changing settings, I have it stable now - pretty sure it was the confetti or one of the shadow slider boxes.

**Comment by T8RIN** [comment] 2024-05-12 08:40
> This was happening while changing settings, I have it stable now - pretty sure it was the confetti or one of the shadow slider boxes.

It's not my fault, jetpack compose issue
