### ISSUE TITLE
[Bug] App Crash: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Alexandru51** [T8RIN/ImageToolbox#1102] opened 2024-05-23 15:07 UTC
I'm the guy who translated this in romanian, so um, when i go to the pick color section and select a image, the app crash, so here's the log ig or idk how to call it

Device: M2003J15SC (Redmi - merlinnfc), SDK: 31 (12), App: 2.8.2-alpha02 (138)java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=2 dst.length=16 dstPos=3 length=-1at java.lang.System.arraycopy(Native Method)at d7.m.j(SourceFile:12)at d0.d.a(SourceFile:16)at M0.G.y(SourceFile:73)at M0.w0.c(SourceFile:7)at c0.q.a(SourceFile:224)at c0.J.e(SourceFile:26)at c0.s.a(SourceFile:36)at c0.J.e(SourceFile:26)at c0.a.c(SourceFile:3)at b0.u.j(SourceFile:51)at b0.u.i(SourceFile:6)at b0.v0.o(SourceFile:188)at N0.b0.doFrame(SourceFile:34)at N0.Y.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1135)at android.view.Choreographer.doCallbacks(Choreographer.java:920)at android.view.Choreographer.doFrame(Choreographer.java:829)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:210)at android.os.Looper.loop(Looper.java:299)at android.app.ActivityThread.main(ActivityThread.java:8280)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)Suppressed: T8.g: [N0.c0@a51c676, N0.F0@48da477, t0{Cancelling}@37578e4, Z@832214d]

**Comment by Alexandru51** [comment] 2024-05-23 15:08
PS: Latest alpha version and file explorer selected as image source

**Comment by T8RIN** [comment] 2024-05-23 15:09
Hi, that's a Duplicate of #1047, not my fault, google just have no testers for their Libraries i think :))

**Closed** 2024-05-23 15:10 UTC
